StockSite/StockSite/urls.py
"""
Definition of urls for StockSite.
"""

from datetime import datetime
from django.contrib import admin
from django.conf.urls import url, include
import django.contrib.auth.views as authViews

import app.forms
import app.views

# Uncomment the next lines to enable the admin:
# from django.conf.urls import include
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = [
    # Examples:
    url(r'^$', app.views.home, name='home'),
    url(r'^contact$', app.views.contact, name='contact'),
    url(r'^about', app.views.about, name='about'),
    url(r'^login/$',
        authViews.login,
        {
            'template_name': 'app/login.html',
            'authentication_form': app.forms.BootstrapAuthenticationForm,
            'extra_context':
            {
                'title': 'Log in',
                'year': datetime.now().year,
            }
        },
        name='login'),
    url(r'^logout$',
        authViews.logout,
        {
            'next_page': '/',
        },
        name='logout'),
    url(r'^register/$',
        app.views.create_user, { }, name='register'),
    url(r'^admin/', admin.site.urls),
    url(r'^robinhood/', include('robinhood.urls', namespace='robinhood'), name='robinhood'),
    url(r'^stock/(?P<stock>[a-zA-Z ]+)/', app.views.stock, name='single_stock'),
]

StockSite/robinhood/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
    #TODO look into having two paths lead to same view, or refactor pathing
    url(r'^signin', views.register_or_login, name='login'),
    url(r'^registration', views.register_or_login, name='registration'),
    url(r'^logout', views.logout, name='logout')
    #url(r'^register', views.register)
]

StockSite/app/forms.py
"""
Definition of forms.
"""

from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.utils.translation import ugettext_lazy as _

class BootstrapAuthenticationForm(AuthenticationForm):
    """Authentication form which uses boostrap CSS."""
    username = forms.CharField(max_length=254,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'User name'}))
    password = forms.CharField(label=_("Password"),
                               widget=forms.PasswordInput({
                                   'class': 'form-control',
                                   'placeholder':'Password'}))

class RegistrationForm(UserCreationForm):
    username = forms.CharField(max_length=254,
                               widget=forms.TextInput({
                                    'class':'form-control',
                                    'placeholder': 'Username'}))
    email = forms.CharField(max_length=254,
                            widget=forms.TextInput({
                                    'class':'form-control',
                                    'placeholder': 'Email'}))
    firstName = forms.CharField(max_length=30,
                                widget=forms.TextInput({
                                    'class':'form-control',
                                    'placeholder': 'First Name'}))
    password1 = forms.CharField(label=_("Password"),
                               widget=forms.PasswordInput({
                                   'class': 'form-control',
                                    'placeholder': 'Password'}))
    password2 = forms.CharField(label=_("Password confirmation"),
                               widget=forms.PasswordInput({
                                   'class': 'form-control',
                                   'placeholder': 'Confirm Password'}))

StockSite/app/templates/app/about.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<p>Use this area to provide additional information.</p>

{% endblock %}

StockSite/app/templates/app/contact.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

{% endblock %}

StockSite/app/templates/app/error.html
<!DOCTYPE html>
{% block content %}
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title>Error</title>
</head>
<body>
    <h2>Error</h2>
    <p>{{ error }}</p>
</body>
</html>
{% endblock %}

StockSite/app/templates/app/index.html
{% extends "app/layout.html" %}
{% load static %}
{% block content %}
<head>
    <script type="text/javascript">
    var stocks = {{ stock_json|safe }};
    updateStockInfo(stocks);        
    </script>
</head>
<body>
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <h1 class="page-header"><span>Dashboard</span><span class="pull-right glyphicon glyphicon-refresh" onclick="updateStockInfo(stocks)"></span></h1>
        
        <div class="row">              
            <div class="col-sm-4">
                <canvas id="chart" ></canvas>
            </div>
            <div class="col-sm-4">
                <canvas id="chart2" ></canvas>
            </div>
            <div class="col-sm-4">
                <canvas id="chart3" ></canvas>
            </div>
        </div>
        <h2 class="sub-header">Your Stocks</h2>
        <div class="table-responsive">
        <table id ="portfolioTable" class="table table-striped">
            <thead>
                <tr>
                    <th>Ticker</th>
                    <th>Name</th>
                    <th>Price</th>
                    <th>1 Day Movement</th>
                    <th>5 Day</th>
                    <th>1 Month</th>
                    <th>Chart</th>
                </tr>
            </thead>
            <tbody id="portfolioStocks">
                {% for stock in stock_list %}
                    <tr name="{{stock.symbol}}">
                        <td><a href="{% url 'single_stock' stock=stock.symbol %}">{{ stock.symbol }}</a></td>
                        <td>{{ stock.name }}</td>
                        <td>${{ stock.current_price }}</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>
                            <a ticker="{{stock.symbol}}" onclick="getChart(this.getAttribute('ticker'), 'chart')">1</a>
                            <a ticker="{{stock.symbol}}" onclick="getChart(this.getAttribute('ticker'), 'chart2')">2</a>
                            <a ticker="{{stock.symbol}}" onclick="getChart(this.getAttribute('ticker'), 'chart3')">3</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>              
        </table>
        </div>
    </div>
</body>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static "app/scripts/bootstrap.min.js" %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.0/Chart.bundle.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.0/Chart.bundle.min.js"></script>
    <script type="text/javascript">
        var stockRows = document.getElementById('portfolioStocks').getElementsByTagName('tr');
        getChart(stockRows[0].getElementsByTagName('td')[0].textContent, "chart");
        getChart(stockRows[1].getElementsByTagName('td')[0].textContent, "chart2");
        getChart(stockRows[2].getElementsByTagName('td')[0].textContent, "chart3");
    </script>      

{% endblock %}

StockSite/app/templates/app/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="A dashboard for stock trading.">
    <meta name="author" content="Matt S.">

    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}" />
    <script src="{% static 'app/scripts/modernizr-2.6.2.js' %}"></script>

    <!-- Custom styles for this template -->
    <link href="{% static "app/content/dashboard.css" %}" rel="stylesheet"> 
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="{% static "app/scripts/stockhelper.js" %}"></script>
    <script src="{% static "app/scripts/charthelper.js" %}"></script>
    <link rel="icon" href="../../favicon.ico">

    <title>{{ Title }}</title>
</head>

<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'home' %}">Stock Dashboard</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'home' %}">Dashboard</a></li>
                <li><a href="#">Settings</a></li>
                {% if not has_robinhood and request.user.is_authorized %}
                <li><a href="{% url 'robinhood:registration' %}">Register for Robinhood</a></li>
                {% elif has_robinhood and rh_loggedin %}
                <li class="dropdown">
                    <a href="#" data-toggle="dropdown" class="dropdown-toggle">{{ request.user.robinhooduser.username }} <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'robinhood:logout' %}">Sign out of Robinhood</a></li>
                    </ul>
                </li>
                {% elif has_robinhood and not rh_loggedin %}
                <li><a href="{% url 'robinhood:login' %}">Sign in to Robinhood</a></li>
                {% endif %}
                {% if request.user.is_authenticated %}
                <li><a href="{% url "logout" %}">Log Out</a></li>
                {% else %}
                <li><a href="{% url "login" %}">Log In</a></li>
                {% endif %}
                <li><a href="#">Help</a></li>
                </ul>
                <form class="navbar-form navbar-right">
                <input type="text" class="form-control" placeholder="Search...">
                </form>
            </div>
        </div>
    </nav>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav nav-sidebar">
                <li class="active"><a href="#">Overview <span class="sr-only">(current)</span></a></li>
                <li><a href="#">Portfolio</a></li>
                <li><a href="#">History</a></li>
                <li><a href="#">Export</a></li>
            </ul>
            <ul class="nav nav-sidebar">
                <li><a href="">Stock</a></li>
                <li><a href="">News</a></li>
                <li><a href="">Top Gainers</a></li>
                <li><a href="">Top Losers</a></li>
            </ul>
        </div>
        {% block content %}
        {% endblock %}
      </div>
    </div>
</body>
</html>

StockSite/app/templates/app/login.html
{% extends "app/layout.html" %}

{% block content %}
<body>
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
    <h2>{{ title }}</h2>
    <section id="loginForm">
        <form action="." method="post" class="form-horizontal">
            {% csrf_token %}
            <h4>Use a local account to log in.</h4>
            <hr />
            <div class="form-group">
                <label for="id_username" class="col-md-2 control-label">User name</label>
                <div class="col-md-10">
                    {{ form.username }}
                </div>
            </div>
            <div class="form-group">
                <label for="id_password" class="col-md-2 control-label">Password</label>
                <div class="col-md-10">
                    {{ form.password }}
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="hidden" name="next" value="/" />
                    <input type="submit" value="Log in" class="btn btn-default" />
                    <div>Don't have an account? <a href="{% url 'register' %}">Sign up here.</a></div>
                </div>
            </div>
            {% if form.errors %}
            <p class="validation-summary-errors">Please enter a correct user name and password.</p>
            {% endif %}
        </form>
    </section>
</div>
</body>
{% endblock %}


{% block scripts %}

    {% load staticfiles %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

StockSite/app/templates/app/stock.html
{% extends "app/layout.html" %}
{% load static %}
{% load humanize %}
{% block content %}

<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
    <h1 class="page-header"><span>{{ stock_info.name}} - $</span><span id="stock_price"></span><span class="pull-right glyphicon glyphicon-refresh" onclick="updateStockInfo(stock)"></span></h1>
    <div class="row">

    </div>
    <div class="row">   
        <div class="col-sm-10 cox-xs-12">
            <canvas id="chart4" ></canvas>
        </div>
        <div class="col-sm-2 col-xs-12">
            <ul class="list-group">
                <li class="list-group-item">
                    <table class="table">
                        <tr><th># Held</th><th>Avg Price</th></tr>
                        <tr><td>{{ user_stake.quantity|floatformat:0 }}</td><td>{{ user_stake.average_buy_price|floatformat:2 }}</td></tr>
                    </table>
                </li>
                <li class="list-group-item">
                    <table class="table">
                        <tr><th colspan="2">Day</th></tr>
                        <tr><td>+3.00</td><td>+8.24%</td></tr>
                    </table>                        
                </li>
                <li class="list-group-item">
                    <table class="table">
                        <tr><th colspan="2">Week</th></tr>
                        <tr><td>5.00</td><td>+3.2%</td></tr>
                    </table>
                </li>
                <li class="list-group-item">
                    <table class="table">
                        <tr><th colspan="2">Month</th></tr>
                        <tr><td>-2.00</td><td>-1.8%</td></tr>
                    </table>
                </li>
            </ul>
        </div>
    </div>
    <div class="row">
        <h4>Fundamentals</h4>
        <ul class="list-group">
            <li class="list-group-item">
                <ul class="list-group-horizontal">
                    <li class="list-group-item" id="volume"></li>
                    <li class="list-group-item" id="PE"></li>
                    <li class="list-group-item" id="52High"></li>
                    <li class="list-group-item" id="52Low"></li>
                </ul>
            </li>
        </ul>
    </div>
</div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.0/Chart.bundle.min.js"></script>
    <script type="text/javascript">
        getChart('{{ stock_info.symbol }}', "chart4");
        updateStockFundamentals('{{ stock_info.symbol }}');
        updateStockPrice('{{ stock_info.symbol }}');
    </script> 

{% endblock %}

StockSite/app/templates/app/user_registration.html
{% extends "app/layout.html" %}

{% block content %}
<body>
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <h2>{{ title }}</h2>
        <section id="userCreationForm">
            <form action="." method="post" class="form-horizontal">
                {% csrf_token %}
                <h4>Fill out your user information.</h4>
                <div class="form-group">
                    <label for="id_username" class="col-md-2 control-label">User name</label>
                    <div class="col-md-10">
                        {{ form.username }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_email" class="col-md-2 control-label">Email</label>
                    <div class="col-md-10">
                        {{ form.email }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_firstName" class="col-md-2 control-label">First Name</label>
                    <div class="col-md-10">
                        {{ form.firstName }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_password1" class="col-md-2 control-label">Password</label>
                    <div class="col-md-10">
                        {{ form.password1 }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_password2" class="col-md-2 control-label">Confirm Password</label>
                    <div class="col-md-10">
                        {{ form.password2 }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="hidden" name="next" value="/" />
                        <input type="submit" value="Submit" class="btn btn-default" />
                    </div>
                </div>
            </form>
        </section>
    </div>
</body>
{% endblock %}